# flink-py/Dockerfile
FROM apache/flink:1.18.1-scala_2.12-java11

# Instalar Python y herramientas necesarias
RUN apt-get update && apt-get install -y python3 python3-pip

# Instala las dependencias específicas que requieras, por ejemplo:
# COPY requirements.txt /opt/flink/
# RUN pip3 install -r /opt/flink/requirements.txt
